### ISSUE TITLE
Basic Minecraft Combat

### ISSUE THREAD

**Issue by GreatWyrm** [minestommmo/JointMMO#12]
A basic Minecraft melee combat system - including

Damage Handling/Processing
Attribute, Potion Effects, Some Enchantment Modifiers
Immunity Ticks
Cooldown Timer

Note: This will not be including bows at this time, that will most likely be done at a later date

**Comment by mworzala** [comment]
Would say enchants & potion effects should be held off for a little while. Not sure the plan with those
