### ISSUE TITLE
Potential Bug in PlayerImpl

### ISSUE THREAD

**Issue by GreatWyrm** [minestommmo/JointMMO#45]
The function handlePacket does not appear to have a filter on what PlayerPackets it processes, and may process packets for other players.

I have not tested this, and I would like this tested.

**Comment by mworzala** [comment]
It uses the `EventNode` from the player, which is mapped (local) to that entity. From the Entity constructor:
```java
this.eventNode = process.eventHandler().map(this, EventFilter.ENTITY);
```
